name: Build on Tag Push for Release Branches

on:
  push:

    tags:

      - 'release/*'  # Matches tags like release/v1.0.0, release/v2.0.0

jobs:
  build:
    runs-on: self-hosted

    steps:


      - name: Print the Tag Triggered
        run: |
          echo "Tag Triggered"
